version: "3.9"

services:
  web:
    build: .
    container_name: django_web
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn digital_marketing_blog.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
